---

argument_specs:
  main:
    short_description: Deploy dotfiles from git repositories
    description:
      - >-
        Deploy dotfiles from git repositories to a specified
        target location.

    author:
      - charlesrocket

    options:
      dotfiles_repo:
        description: URL of the target repository to deploy from.
        type: str
        required: true

      dotfiles_repo_version:
        description: Branch to track.
        type: str
        required: true

      dotfiles_repo_accept_hostkey:
        description:
          - >-
            Ensure "-o StrictHostKeyChecking=no" is present as an
            ssh option.

        type: bool
        default: false

      dotfiles_repo_force:
        description: Force C(git clone) to override local modifications.
        type: bool
        default: false

      dotfiles_repo_local_destination:
        description: Local dotfiles repository target.
        type: str
        default: ~/src/dotfiles

      dotfiles_home:
        description: Local dotfiles deployment target.
        type: str
        default: "~"

      dotfiles_files:
        description: Files to track.
        type: list
        elements: str
        required: true
