---
galaxy_info:
  author: charlesrocket
  description: Dotfiles deployment from Git repositories
  role_name: dotfiles
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: GenericUNIX
      versions:
        - all
    - name: GenericBSD
      versions:
        - all
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - dotfiles
    - git
