---

namespace: charlesrocket
name: essential
version: 1.2.2
readme: README.md
description: Essential Ansible roles
authors:
  - charlesrocket

license:
  - MIT

tags:
  - infrastructure
  - development
  - dotfiles
  - git

repository: https://github.com/charlesrocket/essential-collection
documentation: https://charlesrocket.github.io/essential-collection/
issues: https://github.com/charlesrocket/essential-collection/issues
build_ignore:
  - .github
  - .gitignore
  - molecule
  - requirements*txt
