namespace: charlesrocket
name: essential
version: 1.0.1
readme: README.md
description: Essential Ansible roles
authors:
  - charlesrocket

license:
  - MIT

tags:
  - development
  - dotfiles
  - git

repository: https://github.com/charlesrocket/essential_collection
issues: https://github.com/charlesrocket/essential_collection/issues
build_ignore:
  - .github
  - .gitignore
  - molecule
