---

namespace: charlesrocket
name: essential
version: 1.1.0
readme: README.md
description: Essential Ansible roles
authors:
  - charlesrocket

license:
  - MIT

tags:
  - infrastructure
  - development
  - dotfiles
  - git

repository: https://github.com/charlesrocket/essential_collection
documentation: https://charlesrocket.github.io/essential_collection/
issues: https://github.com/charlesrocket/essential_collection/issues
build_ignore:
  - .github
  - .gitignore
  - molecule
  - requirements*txt
