---
- name: FreeBSD | Install helper dependencies
  ansible.builtin.package:
    name: "{{ helper_dependencies }}"
    state: present
  when: helper_dependencies is defined and git_netrc_helper
  become: true

- name: FreeBSD | Install Git
  ansible.builtin.package:
    name: "{{ git_package }}"
    state: present
  become: true
