---
- name: Ensure helper directory exists
  ansible.builtin.file:
    dest: "{{ git_helper_directory }}"
    state: directory
    mode: 0755
  become: false

- name: Clone git repository
  ansible.builtin.git:
    repo: https://github.com/git/git.git
    dest: "{{ git_repo_destination }}"
    version: master
    depth: 1
  notify:
    - Build git-credential-netrc
    - Deploy git-credential-netrc
