---

- name: Gentoo | Sync repositories
  portage:
    sync: web
  when: ansible_os_family == "Gentoo"
  become: true

- name: Linux | Install dependencies
  ansible.builtin.package:
    name: "{{ dependencies }}"
    state: present
  become: true
  when: dependencies is defined

- name: Linux | Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Linux | Install Git
  ansible.builtin.package:
    name: "{{ git_package }}"
    state: present
  become: true
