---

- name: "~/.config/mc/ini information"
  ansible.builtin.stat:
    path: "~/.config/mc/ini"
  register: test_file1

- name: "~/.zshrc information"
  ansible.builtin.stat:
    path: "~/.zshrc"
  register: test_file2

- name: "~/.xsession information"
  ansible.builtin.stat:
    path: "~/.xsession"
  register: test_file3

- name: "~/bin information"
  ansible.builtin.stat:
    path: "~/bin"
  register: test_file4

- name: "Check ~/.config/mc/ini"
  ansible.builtin.assert:
    that:
      - test_file1.stat.exists
      - test_file1.stat.islnk
      - test_file1.stat.executable == false

- name: "Check ~/.zshrc"
  ansible.builtin.assert:
    that:
      - test_file2.stat.exists
      - test_file2.stat.islnk
      - test_file2.stat.executable == false

- name: "Check ~/.xsession"
  ansible.builtin.assert:
    that:
      - test_file3.stat.exists
      - test_file3.stat.islnk
      - test_file3.stat.executable

- name: "Check ~/bin"
  ansible.builtin.assert:
    that:
      - test_file4.stat.exists
      - test_file4.stat.islnk
      - test_file4.stat.executable
