---
- name: "Build git-credential-{{ git_helper }}"
  ansible.builtin.command:
    "{{ (ansible_system == 'Linux') | ternary('make', 'gmake') }}"
  args:
    chdir: "{{ git_repo_destination }}/contrib/credential/{{ git_helper }}/"

- name: "Deploy git-credential-{{ git_helper }}"
  ansible.builtin.copy:
    src: "{{ git_repo_destination }}/contrib/credential/\
      {{ git_helper }}/git-credential-{{ git_helper }}"
    remote_src: true
    dest: "{{ git_helper_directory }}/git-credential-{{ git_helper }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'
