---

- name: Converge
  hosts: all
  vars:
    git_helper: ["netrc"]
    git_repo_shallow: true

  tasks:
    - name: Include git role
      ansible.builtin.include_role:
        name: "charlesrocket.essential.git"
        apply:
          become: true

    - name: Include dotfiles role
      ansible.builtin.include_role:
        name: "charlesrocket.essential.dotfiles"
