---

- name: OpenBSD | Install helper dependencies
  ansible.builtin.package:
    name: "{{ git_helper_dependencies }}"
    state: present
  when: git_helper_dependencies is defined and git_helper is defined
  become: true

- name: OpenBSD | Install Git
  ansible.builtin.package:
    name: "{{ git_package }}"
    state: present
  become: true
