---

- name: Converge
  hosts: all
  vars:
    git_helper: ["netrc"]
    git_repo_shallow: true
    git_repo_destination: "~/documents/git"
    dotfiles_repo: "https://github.com/charlesrocket/dotfiles.git"
    dotfiles_repo_version: obsd-station
    dotfiles_repo_local_destination: "~/documents/dotfiles"
    dotfiles_files:
      - .config/mc/ini
      - .xsession
      - .zshrc


  tasks:
    - name: Include git role
      ansible.builtin.include_role:
        name: "charlesrocket.essential.git"
        apply:
          become: true

    - name: Include dotfiles role
      ansible.builtin.include_role:
        name: "charlesrocket.essential.dotfiles"
