---
- name: Converge
  hosts: all
  vars:
    git_netrc_helper: true
    git_repo_shallow: true

  tasks:
    - name: Include git_role
      ansible.builtin.include_role:
        name: charlesrocket.git
