---

- name: Verify
  hosts: all
  tasks:
    - name: Include test_dotfiles
      ansible.builtin.include_role:
        name: "test_dotfiles"

    - name: Include test_fetch_vars
      ansible.builtin.include_role:
        name: "test_fetch_vars"
