---

- name: Converge
  hosts: all
  tasks:
    - name: Include git role
      ansible.builtin.include_role:
        name: "charlesrocket.git"
        apply:
          become: true

    - name: Include dotfiles role
      ansible.builtin.include_role:
        name: "charlesrocket.dotfiles"
