---

name: CD
'on':
  workflow_call:
    secrets:
      GALAXY_API_KEY:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Publish
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
