---

name: CI
'on':
  pull_request:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  lint:
    name: lint
    if: "!startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - run: pip3 install yamllint
      - run: yamllint .
      - run: ansible-galaxy collection build
      - run: >-
          ansible-galaxy collection install
          charlesrocket-essential-$(grep version galaxy.yml |
          awk '{print $2}').tar.gz

      - uses: ansible/ansible-lint@main

  ansible-test:
    name: ansible-test
    runs-on: ubuntu-latest
    steps:
      - name: Perform sanity testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: stable-2.17
          testing-type: sanity

      - name: Perform integration testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          testing-type: integration

  docker:
    name: molecule ${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - alpine
          # - rocky

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v5

      - name: Set up Python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: '**/requirements-dev.txt'
          check-latest: true

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run Molecule
        run: molecule test -s linux
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

  release:
    needs: [ansible-test, docker]
    if: |
      github.repository_owner == 'charlesrocket' &&
      startsWith(github.ref, 'refs/tags/')

    uses: ./.github/workflows/cd.yml
    secrets:
      GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}

  docsite:
    needs: [ansible-test, docker]
    permissions:
      contents: read
      pages: write
      id-token: write

    if: |
      github.repository_owner == 'charlesrocket' &&
      startsWith(github.ref, 'refs/tags/')

    uses: ./.github/workflows/docsite.yml
