---

name: CI
'on':
  pull_request:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  lint:
    name: lint
    if: "!startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: pip3 install yamllint
      - run: yamllint .
      - uses: ansible/ansible-lint-action@main

  ansible-test:
    name: ansible-test
    runs-on: ubuntu-latest
    steps:
      - name: Perform sanity testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          testing-type: sanity
      - name: Perform integration testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          testing-type: integration

  vagrant:
    name: molecule ${{ matrix.distro }}
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        distro:
          - freebsd13
          - netbsd9
          - openbsd7

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: '**/requirements-dev.txt'
          check-latest: true

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ matrix.distro }}
          restore-keys: |
            ${{ runner.os }}-vagrant-${{ matrix.distro }}

      - name: Run Molecule
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

  docker:
    name: molecule ${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - alpine
          - rocky

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: '**/requirements-dev.txt'
          check-latest: true

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run Molecule
        run: molecule test -s linux
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

  release:
    needs: [ansible-test, docker, vagrant]
    if: |
      github.repository_owner == 'charlesrocket' &&
      startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/cd.yml
    secrets:
      GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}

  docsite:
    needs: [ansible-test, docker, vagrant]
    permissions:
      contents: read
      pages: write
      id-token: write
    if: |
      github.repository_owner == 'charlesrocket' &&
      startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/docs.yml
