---

name: Linting

'on':
  pull_request:
  push:
  schedule:
    - cron: "0 11 13 */2 *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ansible-community/ansible-lint-action@main
      - run: pip3 install yamllint
      - run: yamllint .
